route = "subdomain"

[mounts.public]
kind = "Persisted"
remote_path = "/usr/src/app/public"
access_mode = "ReadOnly"

[[mounts.public.contents]]

[mounts.public.contents.File]
file_relative_path = "index.html"
contents = """
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>always-fails</title>
</head>
<body>
  <h1>Hello, world! (from always-fails)</h1>
</body>
</html>
"""

[ports]
public = 3000
additional = []

[health_check]
command = "false"
wait_time_in_seconds = 1
