services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    container_name: authentik-postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${AUTHENTIK_PG_DB} -U $${AUTHENTIK_PG_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${AUTHENTIK_PG_PASS}
      - POSTGRES_USER=${AUTHENTIK_PG_USER}
      - POSTGRES_DB=${AUTHENTIK_PG_DB}
    env_file:
      - .env
    networks:
      - backend

  redis:
    image: docker.io/library/redis:alpine
    container_name: authentik-redis
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
    networks:
      - backend

  authentik-server:
    image: ghcr.io/goauthentik/server:2024.6.2
    restart: unless-stopped
    command: server
    environment:
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__USER=${AUTHENTIK_PG_USER}
      - AUTHENTIK_POSTGRESQL__NAME=${AUTHENTIK_PG_DB}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_PG_PASS}
      - AUTHENTIK_ERROR_REPORTING___ENABLED=true
      - AUTHENTIK_ERROR_REPORTING___ENABLED=true
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
    volumes:
      - ./volumes/authentik/media:/media
      - ./volumes/authentik/custom-templates:/templates
      - ./volumes/authentik/override.css:/web/dist/custom.css
    ports:
      - "${COMPOSE_PORT_HTTP:-9000}:9000"
      - "${COMPOSE_PORT_HTTPS:-9443}:9443"

    depends_on:
      - postgresql
      - redis
    networks:
      - frontend
      - backend

  authentik-worker:
    image: ghcr.io/goauthentik/server:2024.6.2
    restart: unless-stopped
    command: worker
    environment:
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__USER=${AUTHENTIK_PG_USER}
      - AUTHENTIK_POSTGRESQL__NAME=${AUTHENTIK_PG_DB}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_PG_PASS}
      - AUTHENTIK_ERROR_REPORTING___ENABLED=true
      - AUTHENTIK_ERROR_REPORTING___ENABLED=true
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/authentik-worker/media:/media
      - ./volumes/authentik-worker/certs:/certs
      - ./volumes/authentik-worker/custom-templates:/templates
    depends_on:
      - postgresql
      - redis
    networks:
      - backend

  traefik:
    image: traefik:v2.11
    ports:
      - 8085:80
      - 8088:8080 # for testing
    volumes:
      - ./volumes/traefik-config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - frontend

  registry:
    image: registry:2.8.3
    ports:
    - "5001:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./volumes/registry:/data

  blue:
    build:
      context: .
      dockerfile: ./hello-world/Dockerfile
    command:
      "npm start"
    environment:
      PORT: 3000
      RESPONSE_MESSAGE: "blue build"
    networks:
      - frontend

  green:
    build:
      context: .
      dockerfile: ./hello-world/Dockerfile
    command:
      "npm start"
    environment:
      PORT: 4000
      RESPONSE_MESSAGE: "green build"
    networks:
      - frontend

volumes:
  database:
  redis:
  authentik_server:
  registry:

networks:
  frontend:
  backend:
