route = "root"

[mounts.public]
kind = "Persisted"
remote_path = "/usr/src/app/public"
access_mode = "ReadOnly"

[[mounts.public.contents]]

[mounts.public.contents.File]
file_relative_path = "index.html"
contents = """
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>hello-world</title>
</head>
<body>
  <h1>Hello, world! (from default)</h1>
</body>
</html>
"""

[mounts.log]
kind = "Persisted"
remote_path = "/var/log/hello-world"
access_mode = "Writable"
rotate_logs = true

[ports]
public = 3000
additional = []

[health_check]
command = '''node -e 'require("http").get("http://localhost:3000/", r => process.exit(r.statusCode === 200 ? 0 : 1)).on("error", () => process.exit(1))' '''
wait_time_in_seconds = 5
