[package]
name = "xtask"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
ed25519-dalek = { version = "2", features = ["rand_core"] }
hex = { workspace = true }
rand = "0.8"
release = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
