#!/usr/bin/env bash
# Runs the whole smoke suite in parallel: one disposable, headless qemu VM per
# scenario, booted from testing-utils/nix/douglas-ci.iso. See CI_QEMU_SMOKE.md
# for how this came to be.
#
# A scenario is a directory under scenarios/; its numbered scripts run in
# order on a fresh VM after setup/ (deploy the binary, `douglas start`).
# Lanes are discovered by globbing scenarios/*/, so a new directory is a new
# lane with no edits here.
#
# The douglas binary is cross-compiled and signed exactly once, on the host,
# before any VM boots; every lane deploys that same file. It is a full debug
# build (debug_assert!, overflow checks, symbols, DWARF) for the most
# information; the 189MB binary and its copies fit because nothing that grows
# lives on the guest's RAM-backed root (see the two disks below).
#
# Every lane gets its own qemu VM (own SSH port, two throwaway disk images:
# /var/lib/douglas, which also holds docker's data, and /home). A lane that
# passes kills its VM and deletes its disks. A lane that FAILS leaves its VM
# running, with its disks, so you can ssh in and look around; the summary
# prints how. Nothing is cleaned up until you run
#   ./ci-fanout.sh --clean
# which stops every leftover VM, deletes their disks and scratch logs, and
# removes the ssh config aliases. A normal run refuses to start while
# leftovers exist (they hold the ports).
#
# Feedback while it runs: every lane phase and every finished step is printed
# as it happens, and a heartbeat every 30s says what each running lane is
# doing.
#
# Audit trail: every run writes testing-utils/smoke-tests/runs/<run id>/
# (gitignored; the newest 10 are kept, and runs/latest points at the last):
#   SUMMARY.md   paste-able report: what was tested, results, failures
#   run.json     the same, machine-readable: exact tree, artifact hashes,
#                host, per-scenario per-step results and failed assertions
#   <scenario>.log             the scenario's full transcript
#   <scenario>.guest-diagnostics.log   guest logs (failed scenarios only)
# Hand SUMMARY.md (and run.json / the failing logs) back when reporting a
# problem. `./ci-fanout.sh --report` prints the latest SUMMARY.md.
#
# Resin's image cache is seeded from a host-side tarball so lanes do not pull
# core images from Docker Hub; see seed-resin-cache.sh.
#
# Usage:
#   ./ci-fanout.sh
#   ./ci-fanout.sh --only upgrade-rollback,woodward-gives-up
#   ./ci-fanout.sh --refresh-cache     # re-seed resin's cache from Docker Hub
#   ./ci-fanout.sh --clean             # stop leftover VMs, delete disks/scratch
#   ./ci-fanout.sh --report            # print the latest run's SUMMARY.md
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

REPO_ROOT="$(cd ../.. && pwd)"
NIX_DIR="$REPO_ROOT/testing-utils/nix"
CI_ISO="$NIX_DIR/douglas-ci.iso"
SSH_KEY="$NIX_DIR/ssh-keys/douglas_id_ed25519"
RESIN_SEED="$NIX_DIR/resin-cache/resin-repositories.tar"
AUDIT_ROOT="$REPO_ROOT/testing-utils/smoke-tests/runs"
AUDIT_KEEP=10
BASE_PORT=2300
SEED_PORT=2390
HEARTBEAT_SECONDS=30

# Host-specific bits, overridable so this is not tied to Apple Silicon: on a
# Linux host set QEMU_BIN/QEMU_ACCEL=kvm/QEMU_BIOS to the distro's paths. The
# guest image is aarch64, so a KVM host must be aarch64 too (an x86_64 host
# would need an x86_64 nix output and a musl target, not built yet).
QEMU_BIN="${QEMU_BIN:-/opt/homebrew/bin/qemu-system-aarch64}"
QEMU_ACCEL="${QEMU_ACCEL:-hvf}"
QEMU_BIOS="${QEMU_BIOS:-/opt/homebrew/share/qemu/edk2-aarch64-code.fd}"
CARGO_TARGET="aarch64-unknown-linux-musl"

BOLD_CYAN=$'\033[1;36m'
BOLD_GREEN=$'\033[1;32m'
BOLD_RED=$'\033[1;31m'
DIM=$'\033[2m'
RESET=$'\033[0m'

RUN_DIR_GLOB="/tmp/douglas-ci-fanout.*"
SSH_CONFIG_MARKER_BEGIN="# BEGIN douglas-ci-fanout (auto-generated by ci-fanout.sh, safe to delete)"
SSH_CONFIG_MARKER_END="# END douglas-ci-fanout"
SSH_CONFIG="$HOME/.ssh/config"

usage() {
    echo "usage: $0 [--only scenario[,scenario...]] [--refresh-cache] [--clean] [--report]" >&2
    exit 2
}

ARGS="$*"
only=""
refresh_cache=0
clean_only=0
report_only=0
while [ $# -gt 0 ]; do
    case "$1" in
        --only) only="${2:-}"; shift 2 || usage ;;
        --refresh-cache) refresh_cache=1; shift ;;
        --clean) clean_only=1; shift ;;
        --report) report_only=1; shift ;;
        *) usage ;;
    esac
done

if [ "$report_only" -eq 1 ]; then
    if [ -f "$AUDIT_ROOT/latest/SUMMARY.md" ]; then
        cat "$AUDIT_ROOT/latest/SUMMARY.md"
        echo
        echo "(full audit trail: $(cd "$AUDIT_ROOT/latest" && pwd -P))"
        exit 0
    fi
    echo "no runs recorded yet under $AUDIT_ROOT" >&2
    exit 1
fi

command -v jq >/dev/null || { echo "jq is required (brew install jq)" >&2; exit 1; }

# --- vm bookkeeping --------------------------------------------------------
# Kill a VM by pidfile, but only if the pid is still a qemu (a stale pidfile
# must never take out an unrelated process that reused the number).
kill_vm() {
    local pidfile="$1" pid
    [ -f "$pidfile" ] || return 0
    pid="$(cat "$pidfile" 2>/dev/null || true)"
    if [ -n "$pid" ] && ps -p "$pid" -o comm= 2>/dev/null | grep -q qemu; then
        kill "$pid" >/dev/null 2>&1
    fi
}

vm_alive() {
    local pidfile="$1" pid
    [ -f "$pidfile" ] || return 1
    pid="$(cat "$pidfile" 2>/dev/null || true)"
    [ -n "$pid" ] && ps -p "$pid" -o comm= 2>/dev/null | grep -q qemu
}

strip_ssh_config_block() {
    if [ -f "$SSH_CONFIG" ] && grep -qF "$SSH_CONFIG_MARKER_BEGIN" "$SSH_CONFIG"; then
        awk -v b="$SSH_CONFIG_MARKER_BEGIN" -v e="$SSH_CONFIG_MARKER_END" \
            'index($0,b){skip=1} !skip{print} index($0,e){skip=0}' \
            "$SSH_CONFIG" >"$SSH_CONFIG.ci-fanout-tmp" && mv "$SSH_CONFIG.ci-fanout-tmp" "$SSH_CONFIG"
    fi
}

leftover_vms() {
    local dir pidfile
    for dir in $RUN_DIR_GLOB; do
        [ -d "$dir" ] || continue
        for pidfile in "$dir"/*.pid; do
            vm_alive "$pidfile" && echo "$pidfile"
        done
    done
}

clean_everything() {
    local dir pidfile
    for dir in $RUN_DIR_GLOB; do
        [ -d "$dir" ] || continue
        for pidfile in "$dir"/*.pid; do
            kill_vm "$pidfile"
        done
    done
    sleep 1
    for dir in $RUN_DIR_GLOB; do
        [ -d "$dir" ] || continue
        rm -rf "$dir"
    done
    strip_ssh_config_block
    echo "stopped every leftover VM, deleted their disks and scratch logs, removed the ssh aliases"
    echo "(audit trails under $AUDIT_ROOT are kept)"
}

if [ "$clean_only" -eq 1 ]; then
    clean_everything
    exit 0
fi

leftovers="$(leftover_vms)"
if [ -n "$leftovers" ]; then
    echo "${BOLD_RED}VMs from a previous run are still up (they hold the ports):${RESET}" >&2
    echo "$leftovers" >&2
    echo "run '$0 --clean' to stop them and delete their disks" >&2
    exit 1
fi

# --- preflight -------------------------------------------------------------
if [ ! -f "$CI_ISO" ]; then
    echo "missing $CI_ISO — build it first (see CI_QEMU_SMOKE.md)" >&2
    exit 1
fi
if [ ! -x "$QEMU_BIN" ]; then
    echo "missing qemu at $QEMU_BIN (set QEMU_BIN; on macOS: brew install qemu under /opt/homebrew)" >&2
    exit 1
fi

# --- lanes -----------------------------------------------------------------
LANES=()
for scenario_dir in scenarios/*/; do
    LANES+=("$(basename "$scenario_dir")")
done

lane_selected() {
    local name="$1" wanted
    [ -z "$only" ] && return 0
    for wanted in ${only//,/ }; do
        [ "$name" = "$wanted" ] && return 0
    done
    return 1
}

RUN_ID="$(date +%Y%m%d-%H%M%S)"
RUN_STARTED_EPOCH="$(date +%s)"
WORKDIR="$(mktemp -d /tmp/douglas-ci-fanout.XXXXXX)"
AUDIT_DIR="$AUDIT_ROOT/$RUN_ID"
mkdir -p "$AUDIT_DIR"
PREBUILT_BINARY="$WORKDIR/douglas-prebuilt"
PROGRESS="$WORKDIR/progress.log"
: >"$PROGRESS"
OUTCOME="aborted"
AUDIT_WRITTEN=0
LANE_NAMES=()
LANE_PORTS=()

# --- operator feedback -----------------------------------------------------
# Lanes append TSV events (epoch, lane, kind, detail) to $PROGRESS; the main
# loop prints whatever is new. No background printer process to clean up.
emit() {
    printf '%s\t%s\t%s\t%s\n' "$(date +%s)" "$1" "$2" "$3" >>"$PROGRESS"
}

PRINTED_LINES=0
print_new_progress() {
    local total epoch lane kind detail color
    total="$(wc -l <"$PROGRESS" | tr -d ' ')"
    [ "$total" -gt "$PRINTED_LINES" ] || return 0
    tail -n +$((PRINTED_LINES + 1)) "$PROGRESS" | while IFS=$'\t' read -r epoch lane kind detail; do
        color="$DIM"
        case "$detail" in
            *" FAIL "*|FAILED*) color="$BOLD_RED" ;;
            *" PASS "*|passed*) color="$BOLD_GREEN" ;;
        esac
        printf '%s  %-42s %s%s%s\n' "$(date -r "$epoch" +%H:%M:%S)" "$lane" "$color" "$detail" "$RESET"
    done
    PRINTED_LINES="$total"
}

heartbeat() {
    local elapsed="$1" done_count=0 running="" name now_text
    for name in "${LANE_NAMES[@]}"; do
        if [ -f "$WORKDIR/$name.status" ]; then
            done_count=$((done_count + 1))
        else
            now_text="$(cat "$WORKDIR/$name.now" 2>/dev/null || echo starting)"
            running="$running $name($now_text)"
        fi
    done
    printf '%s[+%dm%02ds] %d/%d scenarios finished; running:%s%s\n' \
        "$BOLD_CYAN" $((elapsed / 60)) $((elapsed % 60)) "$done_count" "${#LANE_NAMES[@]}" "$running" "$RESET"
}

# --- audit trail -----------------------------------------------------------
steps_json() {
    if [ -s "$WORKDIR/$1.steps.tsv" ]; then
        jq -R -s 'split("\n") | map(select(length > 0) | split("\t")
            | {step: .[0], status: .[1], seconds: (.[2] | tonumber), passes: (.[3] | tonumber), fails: (.[4] | tonumber)})' \
            "$WORKDIR/$1.steps.tsv"
    else
        echo '[]'
    fi
}

failures_json() {
    if [ -s "$WORKDIR/$1.failures.tsv" ]; then
        jq -R -s 'split("\n") | map(select(length > 0) | split("\t") | {step: .[0], text: (.[1:] | join("\t"))})' \
            "$WORKDIR/$1.failures.tsv"
    else
        echo '[]'
    fi
}

lane_json() {
    local name="$1" port="$2" status result seconds
    status="$(cat "$WORKDIR/$name.status" 2>/dev/null || echo none)"
    case "$status" in
        0) result=passed ;;
        none) result=no-result ;;
        *) result=failed ;;
    esac
    seconds="$(cat "$WORKDIR/$name.seconds" 2>/dev/null || echo 0)"
    jq -n --arg name "$name" --argjson port "$port" --arg result "$result" --argjson seconds "$seconds" \
        --argjson steps "$(steps_json "$name")" --argjson failures "$(failures_json "$name")" \
        --arg log "$name.log" --arg alias "douglas-lane-$name" \
        --arg ssh "ssh -i $SSH_KEY -p $port dev@127.0.0.1" \
        --argjson vm_kept "$([ "$result" = failed ] && vm_alive "$WORKDIR/$name.pid" && echo true || echo false)" \
        '{name: $name, result: $result, seconds: $seconds, port: $port, log: $log,
          steps: $steps,
          checks_passed: ($steps | map(.passes) | add // 0),
          checks_failed: ($steps | map(.fails) | add // 0),
          failures: $failures}
         + (if $vm_kept then {kept_vm: {alias: $alias, ssh: $ssh, guest_logs: ($name + ".guest-diagnostics.log")}} else {} end)'
}

tree_json() {
    local dirty tree_hash
    dirty="$(git -C "$REPO_ROOT" status --porcelain | wc -l | tr -d ' ')"
    tree_hash="$( { git -C "$REPO_ROOT" diff HEAD; git -C "$REPO_ROOT" ls-files -o --exclude-standard; } | shasum -a 256 | cut -c1-16)"
    jq -n --arg commit "$(git -C "$REPO_ROOT" rev-parse HEAD)" \
        --arg branch "$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD)" \
        --argjson dirty "$dirty" --arg hash "$tree_hash" \
        '{git_commit: $commit, git_branch: $branch, uncommitted_files: $dirty, uncommitted_changes_hash: $hash}'
}

artifacts_json() {
    local binary_bytes=0 binary_sha="" seed_bytes=0 seed_sha=""
    [ -f "$PREBUILT_BINARY" ] && binary_bytes="$(wc -c <"$PREBUILT_BINARY" | tr -d ' ')" && binary_sha="$(shasum -a 256 "$PREBUILT_BINARY" | cut -d' ' -f1)"
    [ -s "$RESIN_SEED" ] && seed_bytes="$(wc -c <"$RESIN_SEED" | tr -d ' ')" && seed_sha="$(shasum -a 256 "$RESIN_SEED" | cut -d' ' -f1)"
    jq -n --arg bsha "$binary_sha" --argjson bbytes "$binary_bytes" \
        --arg isha "${ISO_SHA:-}" --arg ssha "$seed_sha" --argjson sbytes "$seed_bytes" \
        '{douglas_binary: {sha256: $bsha, bytes: $bbytes, profile: "debug", signed: true},
          ci_iso: {sha256: $isha}, resin_seed: {sha256: $ssha, bytes: $sbytes}}'
}

host_json() {
    jq -n --arg os "$(sw_vers -productVersion 2>/dev/null || uname -s)" --arg arch "$(uname -m)" \
        --arg qemu "$("$QEMU_BIN" --version 2>/dev/null | head -1)" \
        --arg rustc "$(rustc --version 2>/dev/null)" \
        --arg zigbuild "$(cargo zigbuild --version 2>/dev/null | head -1)" \
        --arg accel "$QEMU_ACCEL" \
        '{os: $os, arch: $arch, qemu: $qemu, rustc: $rustc, cargo_zigbuild: $zigbuild,
          vm: {accel: $accel, ram_mb: 2048, vcpus: 2, disks: {"var_lib_douglas": "8G", "home": "4G"}}}'
}

write_summary_md() {
    jq -r '
        def mins: "\(. / 60 | floor)m\(. % 60 | tostring | if length < 2 then "0" + . else . end)s";
        "# Smoke run \(.run_id): \(.outcome | ascii_upcase) in \(.wall_seconds | mins)",
        "",
        "- tree: `\(.tree.git_branch)` @ `\(.tree.git_commit[0:10])`, \(.tree.uncommitted_files) uncommitted files (changes hash `\(.tree.uncommitted_changes_hash)`)",
        "- douglas binary: sha256 `\(.artifacts.douglas_binary.sha256[0:12])`, \(.artifacts.douglas_binary.bytes / 1048576 | floor) MB, debug",
        "- CI image: sha256 `\(.artifacts.ci_iso.sha256[0:12])`; resin seed: sha256 `\(.artifacts.resin_seed.sha256[0:12])`",
        "- host: macOS \(.host.os) \(.host.arch), \(.host.qemu), accel \(.host.vm.accel)",
        "- args: `\(if .args == "" then "(none: every scenario)" else .args end)`",
        "",
        "| scenario | result | time | steps | checks passed | checks failed |",
        "| --- | --- | --- | --- | --- | --- |",
        (.scenarios[] | "| \(.name) | \(.result) | \(.seconds | mins) | \(.steps | length) | \(.checks_passed) | \(.checks_failed) |"),
        "",
        "totals: \(.totals.passed)/\(.totals.scenarios) scenarios passed, \(.totals.steps) steps, \(.totals.checks_passed) checks passed, \(.totals.checks_failed) failed",
        (if (.scenarios | map(select(.result != "passed")) | length) > 0 then
            "", "## Failures",
            (.scenarios[] | select(.result != "passed") |
                "", "### \(.name) (\(.result))",
                (if (.failures | length) > 0 then (.failures[] | "- `\(.step)`: \(.text)") else "- no failed assertion recorded (see the log)" end),
                "- transcript: `\(.log)`",
                (if .kept_vm then
                    "- VM left running: `DOUGLAS_SMOKE_VM=\(.kept_vm.alias)`, `\(.kept_vm.ssh)`",
                    "- guest logs: `\(.kept_vm.guest_logs)`"
                 else empty end))
         else empty end)
    ' "$AUDIT_DIR/run.json" >"$AUDIT_DIR/SUMMARY.md"
}

finalize_audit() {
    [ "$AUDIT_WRITTEN" -eq 0 ] || return 0
    AUDIT_WRITTEN=1
    [ -d "$AUDIT_DIR" ] || return 0
    local name index scenarios_file finished
    finished="$(date +%s)"
    scenarios_file="$WORKDIR/scenarios.json"
    for index in "${!LANE_NAMES[@]}"; do
        lane_json "${LANE_NAMES[$index]}" "${LANE_PORTS[$index]}"
    done | jq -s '.' >"$scenarios_file" 2>/dev/null || echo '[]' >"$scenarios_file"

    jq -n --arg run_id "$RUN_ID" --arg outcome "$OUTCOME" --arg args "$ARGS" \
        --argjson started "$RUN_STARTED_EPOCH" --argjson finished "$finished" \
        --argjson tree "$(tree_json)" --argjson artifacts "$(artifacts_json)" --argjson host "$(host_json)" \
        --slurpfile scenarios "$scenarios_file" \
        '{schema: 1, run_id: $run_id, outcome: $outcome, args: $args,
          started_epoch: $started, finished_epoch: $finished, wall_seconds: ($finished - $started),
          tree: $tree, artifacts: $artifacts, host: $host, scenarios: $scenarios[0],
          totals: {scenarios: ($scenarios[0] | length),
                   passed: ($scenarios[0] | map(select(.result == "passed")) | length),
                   steps: ($scenarios[0] | map(.steps | length) | add // 0),
                   checks_passed: ($scenarios[0] | map(.checks_passed) | add // 0),
                   checks_failed: ($scenarios[0] | map(.checks_failed) | add // 0)}}' \
        >"$AUDIT_DIR/run.json"

    write_summary_md
    for name in "${LANE_NAMES[@]:-}" resin-seed; do
        [ -n "$name" ] || continue
        [ -f "$WORKDIR/$name.log" ] && cp "$WORKDIR/$name.log" "$AUDIT_DIR/$name.log"
        if [ -f "$WORKDIR/$name.status" ] && [ "$(cat "$WORKDIR/$name.status")" != "0" ] && [ -f "$WORKDIR/$name.guest-diagnostics.log" ]; then
            cp "$WORKDIR/$name.guest-diagnostics.log" "$AUDIT_DIR/$name.guest-diagnostics.log"
        fi
    done
    ln -sfn "$RUN_ID" "$AUDIT_ROOT/latest"
    # Keep only the newest AUDIT_KEEP runs so these never pile up.
    ls -1d "$AUDIT_ROOT"/[0-9]*/ 2>/dev/null | sort -r | tail -n +$((AUDIT_KEEP + 1)) | while read -r old; do rm -rf "$old"; done
}

# On EXIT/INT/TERM: a lane with no status file was interrupted mid-run (not a
# test failure), so its VM and disks go. Lanes that passed already cleaned up
# after themselves; lanes that failed stay up on purpose. The ssh aliases and
# scratch dir stay while any failed VM is up, since they are how you reach it.
KEPT=0
cleanup() {
    local name
    finalize_audit
    for name in "${LANE_NAMES[@]:-}" resin-seed; do
        [ -n "$name" ] || continue
        if [ ! -f "$WORKDIR/$name.status" ]; then
            kill_vm "$WORKDIR/$name.pid"
            rm -f "$WORKDIR/$name-state.img" "$WORKDIR/$name-home.img"
        fi
    done
    if [ "$KEPT" -eq 0 ]; then
        sleep 1
        strip_ssh_config_block
        rm -rf "$WORKDIR"
    fi
}
trap cleanup EXIT INT TERM

ISO_SHA="$(shasum -a 256 "$CI_ISO" | cut -d' ' -f1)"

echo "${BOLD_CYAN}=== building douglas once, on the host ===${RESET}"
OUTCOME="build-failed"
(cd "$REPO_ROOT" && cargo zigbuild --target "$CARGO_TARGET" -p douglas) || exit 1
cp "$REPO_ROOT/target/$CARGO_TARGET/debug/douglas" "$PREBUILT_BINARY"
(cd "$REPO_ROOT" && cargo run -p xtask --quiet -- sign "$PREBUILT_BINARY") || exit 1
OUTCOME="aborted"
echo "signed binary: $PREBUILT_BINARY ($(du -h "$PREBUILT_BINARY" | cut -f1))"
echo "audit trail for this run: $AUDIT_DIR"

# An ssh alias per lane so every raw `ssh`/`scp` in the scenarios (several
# bypass ssh_out for stdin piping) reaches the right port with no changes.
echo "$SSH_CONFIG_MARKER_BEGIN" >>"$SSH_CONFIG"
port=$BASE_PORT
for name in "${LANES[@]}"; do
    lane_selected "$name" || { port=$((port + 1)); continue; }
    LANE_NAMES+=("$name")
    LANE_PORTS+=("$port")
    {
        echo "Host douglas-lane-$name"
        echo "    HostName 127.0.0.1"
        echo "    Port $port"
        echo "    User dev"
        echo "    StrictHostKeyChecking accept-new"
        echo "    UserKnownHostsFile $WORKDIR/$name-known-hosts"
    } >>"$SSH_CONFIG"
    port=$((port + 1))
done
{
    echo "Host douglas-lane-resin-seed"
    echo "    HostName 127.0.0.1"
    echo "    Port $SEED_PORT"
    echo "    User dev"
    echo "    StrictHostKeyChecking accept-new"
    echo "    UserKnownHostsFile $WORKDIR/resin-seed-known-hosts"
} >>"$SSH_CONFIG"
echo "$SSH_CONFIG_MARKER_END" >>"$SSH_CONFIG"

# Collected for every lane, pass or fail, so flakiness can be compared with
# healthy runs: every douglas log, docker's journal, containers, memory, OOM
# events and the network path to Docker Hub. Only failed lanes' copies are
# kept in the audit trail.
collect_guest_diagnostics() {
    local name="$1" ssh_opts="$2"
    ssh $ssh_opts dev@127.0.0.1 'bash -s' >"$WORKDIR/$name.guest-diagnostics.log" 2>&1 <<'DIAG'
for f in /var/log/douglas/douglas-cli/douglas-cli.log /var/log/douglas/bract/bract.log /var/log/douglas/resin/resin.log /var/log/douglas/seedbank/seedbank.log /var/log/douglas/woodward/woodward.log; do
  echo "######## $f"; sudo cat "$f" 2>&1
done
echo "######## docker ps -a"; sudo docker ps -a 2>&1
echo "######## journalctl -u docker"; sudo journalctl -u docker --no-pager 2>&1 | tail -200
echo "######## free/df"; free -h; df -h / /var/lib/douglas /home; mount | grep -E " / | /home | /var/lib/douglas "
echo "######## oom"; sudo dmesg | grep -i -E "oom|killed process" || echo none
echo "######## dns/https to docker hub"
getent hosts registry-1.docker.io auth.docker.io 2>&1
curl -sS -m 10 -o /dev/null -w "registry-1 %{http_code} %{time_total}s\n" https://registry-1.docker.io/v2/ 2>&1
curl -sS -m 10 -D - -o /dev/null "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/traefik:pull" 2>&1 | grep -i -E "^HTTP|ratelimit"
DIAG
}

# run_lane <name> <port> <command...> — boots this lane's VM, deploys the
# repo, restores the seeded resin cache, runs the command, and writes the
# result to $WORKDIR/<name>.status. A pass is the final step: the VM is
# killed and its disks deleted. A failure leaves both in place.
run_lane() {
    local name="$1" port="$2"
    shift 2
    local state_disk="$WORKDIR/$name-state.img"
    local home_disk="$WORKDIR/$name-home.img"
    local alias="douglas-lane-$name"
    local ssh_opts="-o LogLevel=ERROR -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=$WORKDIR/$name-known-hosts -i $SSH_KEY -p $port"
    local lane_started=$SECONDS

    {
        echo "[$name] creating disposable disks"
        emit "$name" phase "booting a fresh VM on port $port"
        echo "starting" >"$WORKDIR/$name.now"
        qemu-img create -f raw "$state_disk" 8G >/dev/null
        qemu-img create -f raw "$home_disk" 4G >/dev/null

        echo "[$name] booting on port $port"
        "$QEMU_BIN" \
            -M virt -cpu host -accel "$QEMU_ACCEL" -m 2048 -smp 2 \
            -bios "$QEMU_BIOS" \
            -drive file="$CI_ISO",media=cdrom,readonly=on,file.locking=off,if=virtio \
            -drive file="$state_disk",if=virtio,format=raw,cache=unsafe \
            -drive file="$home_disk",if=virtio,format=raw,cache=unsafe \
            -netdev user,id=net0,hostfwd=tcp::"$port"-:22 -device virtio-net-pci,netdev=net0 \
            -device virtio-serial-pci -chardev stdio,id=char0,signal=off -device virtconsole,chardev=char0 \
            -display none -pidfile "$WORKDIR/$name.pid" &

        local waited=0
        until ssh $ssh_opts -o ConnectTimeout=2 -o BatchMode=yes dev@127.0.0.1 true >/dev/null; do
            if [ "$waited" -ge 90 ]; then
                echo "[$name] SSH never came up after 90s"
                emit "$name" done "FAILED: ssh never came up after 90s"
                echo $((SECONDS - lane_started)) >"$WORKDIR/$name.seconds"
                echo 1 >"$WORKDIR/$name.status"
                exit 1
            fi
            sleep 2
            waited=$((waited + 2))
        done
        echo "[$name] SSH up after ${waited}s"
        emit "$name" phase "up after ${waited}s; copying the example seedlings"
        echo "copying example seedlings" >"$WORKDIR/$name.now"

        rsync -az -e "ssh $ssh_opts" "$REPO_ROOT/example-seedlings/" "dev@127.0.0.1:example-seedlings/"

        if [ -s "$RESIN_SEED" ] && [ "$name" != "resin-seed" ]; then
            echo "[$name] restoring the seeded resin cache"
            emit "$name" phase "restoring the seeded resin cache"
            echo "restoring resin cache" >"$WORKDIR/$name.now"
            ssh $ssh_opts dev@127.0.0.1 \
                'sudo mkdir -p /var/lib/douglas/resin && sudo tar --no-same-owner -C /var/lib/douglas/resin -xpf - && sudo chmod -R a+rX /var/lib/douglas/resin' \
                <"$RESIN_SEED"
        fi

        echo "[$name] running: $*"
        emit "$name" phase "running the scenario"
        DOUGLAS_SMOKE_VM="$alias" \
        DOUGLAS_SMOKE_SSH_KEY="$SSH_KEY" \
        DOUGLAS_SMOKE_PREBUILT_BINARY="$PREBUILT_BINARY" \
        DOUGLAS_SMOKE_LANE="$name" \
        DOUGLAS_SMOKE_PROGRESS_FILE="$PROGRESS" \
        DOUGLAS_SMOKE_NOW_FILE="$WORKDIR/$name.now" \
        DOUGLAS_SMOKE_STEP_LOG="$WORKDIR/$name.steps.tsv" \
        DOUGLAS_SMOKE_FAILURES_LOG="$WORKDIR/$name.failures.tsv" \
            "$@"
        local status=$?

        collect_guest_diagnostics "$name" "$ssh_opts"

        if [ "$status" -eq 0 ]; then
            kill_vm "$WORKDIR/$name.pid"
            rm -f "$state_disk" "$home_disk"
            emit "$name" done "passed in $((SECONDS - lane_started))s"
        else
            echo "[$name] FAILED; leaving its VM running: DOUGLAS_SMOKE_VM=$alias (ssh -i $SSH_KEY -p $port dev@127.0.0.1)"
            emit "$name" done "FAILED after $((SECONDS - lane_started))s; VM left running for inspection"
        fi
        echo $((SECONDS - lane_started)) >"$WORKDIR/$name.seconds"
        echo "$status" >"$WORKDIR/$name.status"
        exit "$status"
    } >"$WORKDIR/$name.log" 2>&1
}

if [ "$refresh_cache" -eq 1 ] || [ ! -s "$RESIN_SEED" ]; then
    echo "${BOLD_CYAN}=== seeding the resin cache from one real VM (talks to Docker Hub once) ===${RESET}"
    mkdir -p "$(dirname "$RESIN_SEED")"
    rm -f "$RESIN_SEED"
    (DOUGLAS_SMOKE_SEED_OUT="$RESIN_SEED" run_lane resin-seed "$SEED_PORT" bash seed-resin-cache.sh)
    print_new_progress
    if [ ! -s "$RESIN_SEED" ]; then
        echo "${BOLD_RED}seeding failed; its VM is left up (DOUGLAS_SMOKE_VM=douglas-lane-resin-seed); log: $WORKDIR/resin-seed.log${RESET}"
        OUTCOME="seed-failed"
        KEPT=1
        exit 1
    fi
fi

echo "${BOLD_CYAN}=== fanning out ${#LANE_NAMES[@]} scenarios ===${RESET}"
run_started_at=$SECONDS
LANE_PIDS=()
for index in "${!LANE_NAMES[@]}"; do
    run_lane "${LANE_NAMES[$index]}" "${LANE_PORTS[$index]}" bash run-scenario.sh "${LANE_NAMES[$index]}" &
    LANE_PIDS+=($!)
done

last_heartbeat=$SECONDS
while :; do
    running=0
    for pid in "${LANE_PIDS[@]}"; do
        kill -0 "$pid" 2>/dev/null && running=1
    done
    print_new_progress
    [ "$running" -eq 1 ] || break
    if [ $((SECONDS - last_heartbeat)) -ge "$HEARTBEAT_SECONDS" ]; then
        heartbeat $((SECONDS - run_started_at))
        last_heartbeat=$SECONDS
    fi
    sleep 2
done
wait
print_new_progress
total_elapsed=$((SECONDS - run_started_at))

echo
echo "${BOLD_CYAN}=== summary (${total_elapsed}s total) ===${RESET}"
overall_status=0
for index in "${!LANE_NAMES[@]}"; do
    name="${LANE_NAMES[$index]}"
    status="$(cat "$WORKDIR/$name.status" 2>/dev/null || echo 1)"
    seconds="$(cat "$WORKDIR/$name.seconds" 2>/dev/null || echo 0)"
    step_count="$(wc -l <"$WORKDIR/$name.steps.tsv" 2>/dev/null | tr -d ' ')"
    check_count="$(awk -F'\t' '{n += $4} END {print n + 0}' "$WORKDIR/$name.steps.tsv" 2>/dev/null)"
    if [ "$status" = "0" ]; then
        echo "${BOLD_GREEN}  passed${RESET}  $name  (${seconds}s, ${step_count:-0} steps, ${check_count:-0} checks)"
    else
        overall_status=1
        KEPT=1
        echo "${BOLD_RED}  FAILED${RESET}  $name  (${seconds}s, ${step_count:-0} steps run)"
        while IFS=$'\t' read -r step text; do
            echo "          failed check in $step: $text"
        done <"$WORKDIR/$name.failures.tsv" 2>/dev/null
        echo "          VM left up: DOUGLAS_SMOKE_VM=douglas-lane-$name  (ssh -i $SSH_KEY -p ${LANE_PORTS[$index]} dev@127.0.0.1)"
    fi
done

if [ "$overall_status" -eq 0 ]; then OUTCOME="passed"; else OUTCOME="failed"; fi
finalize_audit
echo
echo "audit trail: $AUDIT_DIR"
echo "  paste back: $AUDIT_DIR/SUMMARY.md   (details: run.json and the per-scenario logs)"

if [ "$KEPT" -eq 1 ]; then
    echo
    echo "${BOLD_RED}failed scenarios' VMs are still running. When done: $0 --clean${RESET}"
fi

exit "$overall_status"
