[package]
name = "credentials"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = []
mock = ["mockall"]

[dependencies]
log = { workspace = true }
mockall = { workspace = true, optional = true }
nix = { workspace = true, features = ["signal", "user"] }
os = { workspace = true }
thiserror = { workspace = true }
users = { workspace = true }
utils = { workspace = true }

[dev-dependencies]
log = { workspace = true, features = ["mock"] }
mockall = { workspace = true }
