[package]
name = "docker"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = []
mock = ["mockall"]

[dependencies]
async-trait = { workspace = true }
docker_types = { workspace = true }
file_system = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
hyperlocal = "0.9.1"
log = { workspace = true }
mockall = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
shlex = "1.3.0"
simple_rest_client = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
simple_rest_client = { workspace = true, features = ["mock"] }
