[package]
name = "simple_rest_client"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
tokio = {version = "1.44.1", features = ["full"]}
hyper = {version = "1.6.0", features = ["client"]}
http-body-util = "0.1"
hyper-util = { version = "0.1.11", features = ["full"] }
async-trait = "0.1"
colored = "3"
mockall = "0.13.1"

[dev-dependencies]
fake = "4.3.0"
tokio-test = "0.4"
