[package]
name = "bract"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
blueprint = { workspace = true }
bract_types = { workspace = true }
colored = { workspace = true }
config = { workspace = true }
credentials = { workspace = true }
docker = { workspace = true }
docker_types = { workspace = true }
file_system = { workspace = true }
identity = { workspace = true }
log = { workspace = true }
mockall = { workspace = true }
openbao = { workspace = true }
openbao_types = { workspace = true }
os = { workspace = true }
postcard = { version = "1.1.3", features = ["alloc"] }
ram_disk = { workspace = true }
reconcile_trigger_types = { workspace = true }
resin_client = { workspace = true }
resin_types = { workspace = true }
seedbank_client = { workspace = true }
seedbank_types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true }
sha2 = "0.11.0"
subtle = "2.6.1"
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
utils = { workspace = true }
woodward = { workspace = true }

[dev-dependencies]
log = { workspace = true, features = ["mock"] }
file_system = { workspace = true, features = ["mock"] }
identity = { workspace = true, features = ["mock"] }
os = { workspace = true, features = ["mock"] }
credentials = { workspace = true, features = ["mock"] }
docker = { workspace = true, features = ["mock"] }
openbao = { workspace = true, features = ["mock"] }
ram_disk = { workspace = true, features = ["mock"] }
resin_client = { workspace = true, features = ["mock"] }
seedbank_client = { workspace = true, features = ["mock"] }
