[package]
name = "resin_client"
version = "0.1.0"
edition = "2024"

[features]
default = []
mock = ["mockall"]

[dependencies]
async-trait = { workspace = true }
log = { workspace = true, features = ["tui"] }
resin_types = { workspace = true }
docker_types = { workspace = true }
mockall = { workspace = true, optional = true }
simple_rest_client = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
simple_rest_client = { workspace = true, features = ["mock"] }
tokio = { workspace = true, features = ["macros", "rt"] }
