[package]
name = "app"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bract = { path = "./bract" }
clap = "4.5.32"
credentials = { path = "./credentials" }
docker = { path = "./docker" }
file_system = { path = "./file_system" }
log = { path = "./log" }
os = { path = "./os" }
simple_rest_client = { path = "./simple_rest_client" }
tokio = { version = "1.44.1", features = ["full"] }

[workspace]
members = [
    "simple_rest_client",
    "docker",
    "credentials",
    "log",
    "file_system",
    "os",
    "bract",
]

[patch.crates-io]
users = { git = "https://github.com/neilherriford/rust-users", branch = "fix/macos_misaligned-pointer-dereference" }
