[package]
name = "simple_rest_client"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = []
mock = ["mockall"]

[dependencies]
async-trait = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
log = { workspace = true }
mime = { workspace = true }
mockall = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-rustls = "0.26.4"
url = "2.5.8"
urlencoding = "2.1.3"
webpki-roots = "0.26"

[dev-dependencies]
fake = "4.3.0"
tokio-test = "0.4"
log = { workspace = true, features = ["mock"] }
