[package]
name = "simple_rest_client"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = []
mock = ["mockall"]

[dependencies]
tokio = {version = "1.44.1", features = ["full"]}
hyper = {version = "1.6.0", features = ["client"]}
http-body-util = "0.1"
hyper-util = { version = "0.1.11", features = ["full"] }
async-trait = "0.1"
mockall = { version = "0.13.1", optional = true }
urlencoding = "2.1.3"
thiserror = "1"
log = { path = "../log" }

[dev-dependencies]
fake = "4.3.0"
tokio-test = "0.4"
log = { path = "../log", features = ["mock"]}


