log:
  level: TRACE
  format: common

accesslog:
  format: common

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    network: douglas-internal
    exposedByDefault: false
    watch: true
  file:
    directory: /etc/traefik/conf
    watch: true

api:
  dashboard: true
  insecure: true

tracing:
  serviceName: traefik
