[package]
name = "resin"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
axum = { version = "0.8.9", features = ["macros"] }
blueprint = { workspace = true }
config = { workspace = true }
credentials = { workspace = true }
file_system = { workspace = true }
bytes = "1"
hex = "0.4.3"
http-body = "1"
log = { workspace = true, features = ["tui"] }
mime = "0.3.17"
os = { workspace = true }
regex = "1.12.4"
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.11.0"
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
uuid = { workspace = true }

[features]
mock = ["file_system/mock"]

[dev-dependencies]
mockall = { workspace = true }
file_system = { workspace = true, features = ["mock"] }
tower = "0.5"
