[package]
name = "resin"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
axum = { version = "0.8.9", features = ["macros"] }
blueprint = { workspace = true }
config = { workspace = true }
credentials = { workspace = true }
docker_types = { workspace = true }
file_system = { workspace = true }
bytes = "1"
futures-util = "0.3"
hex =  { workspace = true }
http-body = "1"
log = { workspace = true, features = ["tui"] }
mime = { workspace = true }
os = { workspace = true }
refined_string = { workspace = true }
regex = { workspace = true }
reconcile_trigger_client = { workspace = true }
reconcile_trigger_types = { workspace = true }
resin_types = { workspace = true }
seedling_registration_client = { workspace = true }
seedling_registration_types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.11.0"
simple_rest_client = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
uuid = { workspace = true }

[features]
mock = ["file_system/mock", "seedling_registration_client/mock", "reconcile_trigger_client/mock"]

[dev-dependencies]
mockall = { workspace = true }
file_system = { workspace = true, features = ["mock"] }
reconcile_trigger_client = { workspace = true, features = ["mock"] }
seedling_registration_client = { workspace = true, features = ["mock"] }
simple_rest_client = { workspace = true, features = ["mock"] }
tower = "0.5"
