[package]
name = "credentials"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = []
mock = ["mockall"]

[dependencies]
log = { path = "../log" }
os = { path = "../os" }
mockall = { version = "0.13.1", optional = true }
nix = { version = "0.30.1", features = ["signal", "user"] }
thiserror = "1"
users = "=0.11"

[dev-dependencies]
log = { path = "../log", features = ["mock"] }
mockall = { version = "0.13.1" }
