[package]
name = "file_system"
version = "0.1.0"
edition = "2024"

[features]
default = []
mock = ["mockall"]

[dependencies]
async-trait = { workspace = true }
mockall = { workspace = true, optional = true }
nix = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
users = { workspace = true }
utils = { workspace = true }
